name: masterpraktikum
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - aiohttp=3.9.5=py312h98912ed_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - alsa-lib=1.2.12=h4ab18f5_0
  - aom=3.9.1=hac33072_0
  - apptools=5.1.0=pyh44b312d_0
  - attr=2.5.1=h166bdaf_1
  - attrs=23.2.0=pyh71513ae_0
  - aws-c-auth=0.7.22=heee8711_7
  - aws-c-cal=0.7.0=h816f305_0
  - aws-c-common=0.9.23=h4ab18f5_0
  - aws-c-compression=0.2.18=he027950_7
  - aws-c-event-stream=0.4.2=hb72ac1a_14
  - aws-c-http=0.8.2=had8cc17_4
  - aws-c-io=0.14.9=h37d6bf3_5
  - aws-c-mqtt=0.10.4=hb0abfc5_7
  - aws-c-s3=0.6.0=h1f67ec3_0
  - aws-c-sdkutils=0.1.16=he027950_3
  - aws-checksums=0.1.18=he027950_7
  - aws-crt-cpp=0.27.2=heffe44f_0
  - aws-sdk-cpp=1.11.329=habc23cd_8
  - azure-core-cpp=1.12.0=h830ed8b_0
  - azure-identity-cpp=1.8.0=hdb0d106_1
  - azure-storage-blobs-cpp=12.11.0=ha67cba7_1
  - azure-storage-common-cpp=12.6.0=he3f277c_1
  - azure-storage-files-datalake-cpp=12.10.0=h29b5301_1
  - blosc=1.21.6=hef167b5_0
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - brotli-python=1.1.0=py312h30efb56_1
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.32.0=h4ab18f5_0
  - ca-certificates=2024.7.4=hbcca054_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.0=hbb29018_2
  - certifi=2024.7.4=pyhd8ed1ab_0
  - cffi=1.16.0=py312hf06ca03_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - configobj=5.0.8=pyhd8ed1ab_0
  - contourpy=1.2.1=py312h8572e83_0
  - cuda-cudart=12.5.82=he02047a_0
  - cuda-cudart_linux-64=12.5.82=h85509e4_0
  - cuda-nvrtc=12.5.82=he02047a_0
  - cuda-nvtx=12.5.82=he02047a_0
  - cuda-version=12.5=hd4f0392_3
  - cudnn=8.9.7.29=h092f7fd_3
  - cycler=0.12.1=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - datasets=2.20.0=pyhd8ed1ab_0
  - dav1d=1.2.1=hd590300_0
  - dbus=1.13.6=h5008d03_3
  - dill=0.3.8=pyhd8ed1ab_0
  - double-conversion=3.3.0=h59595ed_0
  - eigen=3.4.0=h00ab1b0_0
  - einops=0.8.0=pyhd8ed1ab_0
  - envisage=6.0.1=pyhd8ed1ab_0
  - expat=2.6.2=h59595ed_0
  - ffmpeg=6.1.1=gpl_he2f97eb_114
  - filelock=3.15.4=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_2
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.53.1=py312h41a817b_0
  - freeglut=3.2.2=ha6d2627_3
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - frozenlist=1.4.1=py312h98912ed_0
  - fsspec=2024.5.0=pyhff2d567_0
  - ftfy=6.1.3=pyhd8ed1ab_0
  - fvcore=0.1.5.post20221221=pyhd8ed1ab_0
  - gettext=0.22.5=h59595ed_2
  - gettext-tools=0.22.5=h59595ed_2
  - gflags=2.2.2=he1b5a44_1004
  - gl2ps=1.4.2=hae5d5c5_1
  - glew=2.1.0=h9c3ff4c_2
  - glib=2.80.2=hf974151_0
  - glib-tools=2.80.2=hb6ce0ca_0
  - glog=0.7.1=hbabe93e_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.1.5=py312h1d5cde6_1
  - gnutls=3.7.9=hb077bed_0
  - graphite2=1.3.13=h59595ed_1003
  - gst-plugins-base=1.24.5=hbaaba92_0
  - gstreamer=1.24.5=haf2f30d_0
  - h2=4.1.0=pyhd8ed1ab_0
  - h5py=3.11.0=nompi_py312hb7ab980_102
  - harfbuzz=8.5.0=hfac3d4d_0
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.3=nompi_hdf9ad27_105
  - hpack=4.0.0=pyh9f0ad1d_0
  - huggingface_hub=0.23.4=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=73.2=h59595ed_0
  - idna=3.7=pyhd8ed1ab_0
  - imath=3.1.11=hfc55251_0
  - importlib-metadata=8.0.0=pyha770c72_0
  - importlib_metadata=8.0.0=hd8ed1ab_0
  - importlib_resources=6.4.0=pyhd8ed1ab_0
  - iopath=0.1.9=pyhd8ed1ab_0
  - jasper=4.2.4=h536e39c_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - jsoncpp=1.9.5=h4bd325d_1
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py312h8572e83_1
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.40=hf3520f5_7
  - lerc=4.0.0=h27087fc_0
  - libabseil=20240116.2=cxx17_h59595ed_0
  - libaec=1.1.3=h59595ed_0
  - libarrow=16.1.0=h56e7afd_13_cpu
  - libarrow-acero=16.1.0=he02047a_13_cpu
  - libarrow-dataset=16.1.0=he02047a_13_cpu
  - libarrow-substrait=16.1.0=hc9a23c6_13_cpu
  - libasprintf=0.22.5=h661eb56_2
  - libasprintf-devel=0.22.5=h661eb56_2
  - libass=0.17.1=h8fe9dca_1
  - libblas=3.9.0=22_linux64_openblas
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcap=2.69=h0f662aa_0
  - libcblas=3.9.0=22_linux64_openblas
  - libclang-cpp15=15.0.7=default_h127d8a8_5
  - libclang-cpp18.1=18.1.8=default_h36b48a3_0
  - libclang13=18.1.8=default_h6ae225f_0
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcublas=12.5.3.2=he02047a_0
  - libcufft=11.2.3.61=he02047a_0
  - libcups=2.3.3=h4637d8d_4
  - libcurand=10.3.6.82=he02047a_0
  - libcurl=8.8.0=hca28451_1
  - libcusolver=11.6.3.83=he02047a_0
  - libcusparse=12.5.1.3=he02047a_0
  - libdeflate=1.20=hd590300_0
  - libdrm=2.4.122=h4ab18f5_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.2=h7f98852_5
  - libflac=1.4.3=h59595ed_0
  - libgcc-ng=14.1.0=h77fa898_0
  - libgcrypt=1.11.0=h4ab18f5_0
  - libgettextpo=0.22.5=h59595ed_2
  - libgettextpo-devel=0.22.5=h59595ed_2
  - libgfortran-ng=14.1.0=h69a702a_0
  - libgfortran5=14.1.0=hc5f4f2c_0
  - libglib=2.80.2=hf974151_0
  - libglu=9.0.0=ha6d2627_1004
  - libgoogle-cloud=2.26.0=h26d7fe4_0
  - libgoogle-cloud-storage=2.26.0=ha262f82_0
  - libgpg-error=1.50=h4f305b6_0
  - libgrpc=1.62.2=h15f2491_0
  - libhwloc=2.11.0=default_h5622ce7_1000
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.7=hd590300_0
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=22_linux64_openblas
  - liblapacke=3.9.0=22_linux64_openblas
  - libllvm15=15.0.7=hb3ce162_4
  - libllvm18=18.1.8=hc9dba70_0
  - libmagma=2.7.2=h173bb3b_2
  - libmagma_sparse=2.7.2=h173bb3b_3
  - libnetcdf=4.9.2=nompi_h135f659_114
  - libnghttp2=1.58.0=h47da74e_1
  - libnsl=2.0.1=hd590300_0
  - libnvjitlink=12.5.82=he02047a_0
  - libogg=1.3.5=h4ab18f5_0
  - libopenblas=0.3.27=pthreads_hac2b453_1
  - libopencv=4.10.0=qt6_py312h131ea51_601
  - libopenvino=2024.2.0=h2da1b83_1
  - libopenvino-auto-batch-plugin=2024.2.0=hb045406_1
  - libopenvino-auto-plugin=2024.2.0=hb045406_1
  - libopenvino-hetero-plugin=2024.2.0=h5c03a75_1
  - libopenvino-intel-cpu-plugin=2024.2.0=h2da1b83_1
  - libopenvino-intel-gpu-plugin=2024.2.0=h2da1b83_1
  - libopenvino-intel-npu-plugin=2024.2.0=he02047a_1
  - libopenvino-ir-frontend=2024.2.0=h5c03a75_1
  - libopenvino-onnx-frontend=2024.2.0=h07e8aee_1
  - libopenvino-paddle-frontend=2024.2.0=h07e8aee_1
  - libopenvino-pytorch-frontend=2024.2.0=he02047a_1
  - libopenvino-tensorflow-frontend=2024.2.0=h39126c6_1
  - libopenvino-tensorflow-lite-frontend=2024.2.0=he02047a_1
  - libopus=1.3.1=h7f98852_1
  - libparquet=16.1.0=h9e5060d_13_cpu
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.43=h2797004_0
  - libpq=16.3=ha72fbe1_0
  - libprotobuf=4.25.3=h08a7969_0
  - libre2-11=2023.09.01=h5a48ba9_2
  - libsndfile=1.2.2=hc60ed4a_1
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=14.1.0=hc0a3c3a_0
  - libsystemd0=255=h3516f8a_1
  - libtasn1=4.19.0=h166bdaf_0
  - libtheora=1.1.1=h4ab18f5_1006
  - libthrift=0.19.0=hb90f79a_1
  - libtiff=4.6.0=h1dd3fc0_3
  - libtorch=2.3.1=cuda120_h2b0da52_300
  - libunistring=0.9.10=h7f98852_0
  - libutf8proc=2.8.0=h166bdaf_0
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.48.0=hd590300_0
  - libva=2.22.0=hb711507_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.14.1=hac33072_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.16=hd590300_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.7.0=h2c5496b_1
  - libxml2=2.12.7=hc051c1a_1
  - libzip=1.10.1=h2629f0a_3
  - libzlib=1.3.1=h4ab18f5_1
  - lightning-utilities=0.11.3.post0=pyhd8ed1ab_0
  - llvm-openmp=18.1.8=hf5423f3_0
  - loguru=0.7.2=py312h7900ff3_1
  - lz4-c=1.9.4=hcb278e6_0
  - markupsafe=2.1.5=py312h98912ed_0
  - matplotlib=3.9.1=py312h7900ff3_0
  - matplotlib-base=3.9.1=py312h9201f00_0
  - mayavi=4.8.2=pyqt_py312h6f1e363_305
  - mkl=2023.2.0=h84fe81f_50496
  - mpc=1.3.1=hfe3b2da_0
  - mpfr=4.2.1=h9458935_1
  - mpg123=1.32.6=h59595ed_0
  - mpmath=1.3.0=pyhd8ed1ab_0
  - msgpack-python=1.0.8=py312h2492b07_0
  - multidict=6.0.5=py312h98912ed_0
  - multiprocess=0.70.16=py312h98912ed_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.3.0=hf1915f5_4
  - mysql-libs=8.3.0=hca2cd23_4
  - nccl=2.22.3.1=hbc370b7_0
  - ncurses=6.5=h59595ed_0
  - nettle=3.9.1=h7ab15ed_0
  - networkx=3.3=pyhd8ed1ab_1
  - nlohmann_json=3.11.3=h59595ed_0
  - nspr=4.35=h27087fc_0
  - nss=3.102=h593d115_0
  - numpy=1.26.0=py312heda63a1_0
  - ocl-icd=2.3.2=hd590300_1
  - opencv=4.10.0=qt6_py312hac6a15e_601
  - openexr=3.2.2=haf962dd_1
  - openh264=2.4.1=h59595ed_0
  - openjpeg=2.5.2=h488ebb8_0
  - openssl=3.3.1=h4ab18f5_1
  - orc=2.0.1=h17fec99_1
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.2.2=py312h1d6d2e6_1
  - pcre2=10.43=hcad00b1_0
  - pillow=10.4.0=py312h287a98d_0
  - pip=24.0=pyhd8ed1ab_0
  - pixman=0.43.2=h59595ed_0
  - ply=3.11=pyhd8ed1ab_2
  - portalocker=2.10.0=py312h7900ff3_0
  - proj=9.3.1=h1d62c97_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pugixml=1.14=h59595ed_0
  - pulseaudio-client=17.0=hb77b528_0
  - py-opencv=4.10.0=qt6_py312h071dcc1_601
  - pyarrow=16.1.0=py312h9cebb41_4
  - pyarrow-core=16.1.0=py312h70856f0_4_cpu
  - pyarrow-hotfix=0.6=pyhd8ed1ab_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pyface=8.0.0=pyhd8ed1ab_1
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pyqt=5.15.9=py312h949fe66_5
  - pyqt5-sip=12.12.2=py312h30efb56_5
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.12.4=h194c7f8_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python-xxhash=3.4.1=py312h98912ed_0
  - python_abi=3.12=4_cp312
  - pytorch=2.3.1=cuda120_py312h26b3cf7_300
  - pytorch-lightning=2.3.3=pyhd8ed1ab_0
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py312h98912ed_1
  - qhull=2020.2=h434a139_3
  - qt-main=5.15.8=ha2b5568_22
  - qt6-main=6.7.2=h0f8cd61_2
  - re2=2023.09.01=h7f4b329_2
  - readline=8.2=h8228510_1
  - regex=2024.5.15=py312h9a8786e_0
  - requests=2.32.3=pyhd8ed1ab_0
  - s2n=1.4.17=he19d79f_0
  - safetensors=0.4.3=py312h4b3b743_0
  - setuptools=70.2.0=pyhd8ed1ab_0
  - sip=6.7.12=py312h30efb56_0
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.5.1=h9b69904_2
  - snappy=1.2.1=ha2e4443_0
  - sqlite=3.46.0=h6d4b2fc_0
  - svt-av1=2.1.0=hac33072_0
  - sympy=1.12.1=pypyh2585a3b_103
  - tabulate=0.9.0=pyhd8ed1ab_1
  - tbb=2021.12.0=h434a139_2
  - tbb-devel=2021.12.0=h2069b90_2
  - termcolor=2.4.0=pyhd8ed1ab_0
  - timm=1.0.7=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tokenizers=0.19.1=py312hfef1a59_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - torchmetrics=1.4.0.post0=pyhd8ed1ab_0
  - torchvision=0.18.1=cuda120py312hb04d961_1
  - tornado=6.4.1=py312h9a8786e_0
  - tqdm=4.66.4=pyhd8ed1ab_0
  - traits=6.4.3=py312h98912ed_0
  - traitsui=8.0.0=pyhd8ed1ab_0
  - transformers=4.42.3=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - tzdata=2024a=h0c530f3_0
  - urllib3=2.2.2=pyhd8ed1ab_1
  - utfcpp=4.0.5=ha770c72_0
  - vtk=9.3.1=qt_py312h1234567_200
  - vtk-base=9.3.1=qt_py312h1234567_200
  - vtk-io-ffmpeg=9.3.1=qt_py312h1234567_200
  - wayland=1.23.0=h5291e77_0
  - wayland-protocols=1.36=hd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - wslink=2.1.1=pyhd8ed1ab_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.1=hb711507_2
  - xcb-util-cursor=0.1.4=h4ab18f5_2
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.42=h4ab18f5_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.9=hb711507_1
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxt=1.3.0=hd590300_1
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xf86vidmodeproto=2.3.1=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xxhash=0.8.2=hd590300_0
  - xz=5.2.6=h166bdaf_0
  - yacs=0.1.8=pyhd8ed1ab_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.9.4=py312h98912ed_0
  - zipp=3.19.2=pyhd8ed1ab_0
  - zlib=1.3.1=h4ab18f5_1
  - zstandard=0.22.0=py312h5b18bf6_1
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - decord==0.6.0
      - slideio==2.6.0
      - types-regex==2024.5.15.20240519
prefix: /home/mathias/.conda/envs/masterpraktikum
